// 2022-2026 © Lightingale Community
// Licensed under GNU LGPL v3.0 license.

/** Robust compatibility shims for existing MIDI parsers/converters, powered by the Musical Instructions Compiler Collection from the Octavia project. The shims do not incorporate any code from the original implementations, only attempting to mimic their shapes and behaviour via blackbox experiments.
*
* Shims for the following packages are available.
* - Colxi: `colxi/midi-parser-js`
* - MJT: `chrisguttandin/midi-json-parser` (WIP)
* - MJT: `midi-json-tools/midi-to-json` (WIP)
* - jasmid: `gasman/jasmid/midifile.js` (WIP)
* - jasmid: `carter-thaxton/midi-file` (WIP)
* - jasmid: `ryohey/midifile-ts` (WIP)
*
* For additional benefits, such as [extensive file import and export support](https://kb.ltgc.cc/octavia/impl/format.html) and MIDI 2.0 wire format support, provided by the MICC subsystem, or such as synth behaviour emulation, and extended standard compliance, provided by the Octavia state engine, we strongly recommend you to migrate to Octavia MICC ([Codeberg](https://codeberg.org/ltgc/octavia/), [GitHub](https://github.com/ltgcgo/octavia/), [JSR](https://jsr.io/@ltgc/octavia/doc/micc/)) instead, which can integrate strongly with the rest of the Octavia ecosystem.
*
* This module is also released standalone as `@ltgc/midi-parser-ecosystem` on various registries, to allow transitioning off Node-centric ecosystems to web-compliant ESM, as well as for SEO due to poor existing search index ranking on package manager repositories and search engines. This module does **not** incorporate code generated by LLMs.
*
* @example
* ```js
* // Colxi MIDI Parser
* import {ColxiMIDIParser} from "path_to_js_file";
* const midiFile = await ColxiMIDIParser.parse(input);
* // MIDI JSON Tools Parser or C. Guttandin MIDI JSON Parser
* import {MidiJsonTools} from "path_to_js_file";
* const midiFile = await MidiJsonTools.midiToJson(input); // MIDI JSON Tools
* const midiFile = await MidiJsonTools.parseArrayBuffer(input); // C. Guttandin
* ```
* @license LGPL-3.0-only
* @module cc.ltgc.octavia.miccCompat
*/

import type {
	uint8,
	uint16,
	uint32,
	int16
} from "../../libs/seamstress@ltgcgo/nativeType/index.d.mts";
import type {
	UnifiedBinaryIntake
} from "../micc/index.d.mts";

// `colxi/midi-parser-js`

/** A MIDI event in the `colxi/midi-parser-js` scheme. */
declare interface ColxiMIDIEvent {
	/** MIDI channel. */
	channel?: uint8;
	/** MIDI delta time. */
	deltaTime: uint32;
	/** MIDI event type. Note that event type `240` (SysEx) from MICC will be converted to type `15` (`f`) instead to match behaviour. */
	type: uint8;
	/** If the event is a meta event (`ff` events), the meta event type. */
	metaType?: uint8;
	/** Actual data of the event.
	* ## Channel events
	* - For `8`, `9`, `a`, `b` and `e` events, this is always a two-element `Uint8Array`.
	* - For `c` and `d` events, this is always `uint8`.
	* - For `f` (new SysEx) events, unless altered by the customised interpreter method, this defaults to `Uint8Array`.
	* ## Meta events
	* For `ff` (meta) events, the value type depends on the meta event type in the following order.
	* - For `2f` (track end), this is undefined.
	* - For `21` (track port), this is always `uint8`.
	* - For `59` (key signature), this is always `uint16`.
	* - For `51` (tempo), this is always `uint32`.
	* - For `54` (SMPTE offset) and `58` (time signature), this is always `Uint8Array` from the raw event bytes.
	* - For meta events MICC parses into strings (e.g. text events), this will also be a string.
	* - For all other events, unless altered by the customised interpreter method, the raw event data is passed through as `Uint8Array` by default. */
	data?: uint8|uint16|uint32|Uint8Array|string;
}
/** A MIDI track containing events in the `colxi/midi-parser-js` scheme. */
declare interface ColxiMIDITrack {
	/** List of events populated by the track. */
	event: ColxiMIDIEvent[];
	/** The type of the track. Not present in the original implementation. */
	type: string;
}
/** The representation of a parsed MIDI file in the `colxi/midi-parser-js` scheme. */
declare interface ColxiMIDIFile {
	/** MIDI file type (0, 1, 2). */
	formatType: uint16;
	/** The time division used by files.
	* - When the value is a single `uint16`, this is in TPQN mode. 480 is the most common TPQN value.
	* - When the value is a two-element `uint8` array, this is in SMPTE mode. The first element is the SMPTE frame rate (not guaranteed to be the true frame rate), and the second element is the number of ticks existing per frame. */
	timeDivision: uint16|[uint8, uint8];
	/** Number of expected tracks specified by the MIDI file. Not guaranteed to the the exact number of tracks supplied by the MIDI file. */
	tracks: uint16;
	/** Actual tracks with events. */
	track: ColxiMIDITrack[];
}
/** View into each Colxi MIDI event, supplied to `ColxiMIDIParser.customInterpreter`. Will only be supplied for 0xf0 events. */
declare interface ColxiMIDIView {
	/** The data of the event. Unlike the original implementatino, this only grants view of the current event. */
	data: DataView;
	/** The pointer of the current event. When invoked, for 0xf0 events, the pointer will sit on the SysEx length byte. */
	pointer: number;
	/** Move the apparent pointer. Unlike the original implementation, this method does not affect MIDI file parsing in any way, and is bound-checked.
	* @param offset The relative offset to move the pointer against. -1 moves the pointer to the previous byte, 0 has no effect, and 1 moves the pointer to the next byte.
	* @returns The mutated pointer. */
	movePointer(offset: number): number;
	/** Read multi-byte integers. */
	readInt(readSize: number): number;
	/** Read VLV-8 on the current pointer. */
	readIntVLV(): number;
	/** Read a string. If the `decoders` property of the parser object can be accessed, it will attempt to decode string supplied by the decoders in the `decoders` property, advancing to the next one whenever the current decoder fails. The catch-all decoder is X-ASCII. */
	readStr(readSize: number): string;
}
/** Custom interpreters in Colxi. */
declare type ColxiMIDICustomInterpreter = (
	/** The event type. */
	type: number,
	/** A view into the MIDI data currently being parsed. */
	view: ColxiMIDIView,
	/** Length of the meta event. Will only be present for 0xff events. */
	metaLength?: number
) => any;
/** Shared properties for both variants. */
declare class ColxiMIDIParserBase {
	/** When `true`, this enables verbose debugging logs. This is a hidden property in the original implementation. Defaults to `false`. */
	static debug: boolean;
	/** Defines custom interpreter behaviour. This should only be invoked by the parser.
	*
	* The returned value will populate the data property. Like the original implementation, you are not supposed to return `Promise`s.
	* - If this method returns `true`, or if the property is set to `true`, the default MICC behaviour (`Uint8Array` passthrough) will be assumed. This is the default behaviour, which does not exist in the original implementation.
	* - If this methods returns `false`, `null` or `undefined`, or if the property is set to the same values, the default safer Colxi behaviour (read the last four bytes as `int32`) will be assumed. */
	static customInterpreter?: boolean|ColxiMIDICustomInterpreter;
	/** A list of text decoders to be used. Not present in the original implementation, this is added to allow correct decoding of MIDI files having multiple text encodings, a practical defense against Mojibake. */
	static decoders?: Iterable<TextDecoder>;
	/** When `true`, the parser will also include extensions not seen in regular MIDI files that MICC supports (e.g. XF, MUSEQ). Defaults to `true`.
	*
	* Not present in the original implementation. */
	static extended: boolean;
}
/** (WIP) Mostly a drop-in replacement for the unmaintained `colxi/midi-parser-js`. If some files are proven to be problematic for the original implementation (e.g. with running status omission, event byte overconsumption crash), migrating to Octavia's compatibility layer may help handle those files.
*
* While recommended, this variant nonetheless is mostly a wrapper around parsed MICC sequences to minimise resource usage during parsing, as such it is slower than the original implementation, at around 25% of the original throughput. If the lower throughput is not ideal, `ColxiMIDIParserBuffered` can be used as an alternative that throws resource constraint into the wind to prioritise speed.
*
* For extensive additional benefits, we strongly recommend you to migrate to Octavia MICC instead, which can integrate strongly with the rest of the Octavia ecosystem. This compatibility layer only provides up-to-date SMF support (type 0, type 1, type 2; you also get free MUSEQ and XF extension support by migrating to this compatibility shim). */
export class ColxiMIDIParser extends ColxiMIDIParserBase {
	/** Parses the input into a structured representation.
	*
	* Note that unlike the original, this method is asynchronous. If the synchronous callback is not used, this requires an `await` statement or other ways to handle `Promise`s. This is due to the MICC internals prioritise the use of streams to minimise unnecessary resource usage.
	* 
	* Because the MICC internals for file parsing upholds correctness quite strictly, malformed MIDI data accepted by the original implementation may become rejected by this shim.
	* @param input MIDI file data to be parsed. Like in the original implementation, this can be a Base64 string, one of the two `uint8` arrays, and a file input DOM object. This parser additionally supports an `ArrayBuffer`, a `File` object, or readable byte streams.
	* @param callback The method to invoke when parsing is finished. */
	static parse(input: UnifiedBinaryIntake, callback?: (file: ColxiMIDIFile) => void): Promise<ColxiMIDIFile>;
}
/** (WIP) Mostly a drop-in replacement for the unmaintained `colxi/midi-parser-js`. If some files are proven to be problematic for the original implementation (e.g. with running status omission, event byte overconsumption crash), migrating to Octavia's compatibility layer may help handle those files.
*
* While not recommended, if the speed of `ColxiMIDIParser` isn't up to your taste, this is offered as an alternative to the mentioned implementation. This implementation bypasses `MICCSequence` entirely to directly operate with the MICC internals via fully buffered chunks, avoiding overhead introduced by the regulated reads necessary for limiting resource usage.
*
* For extensive additional benefits, we strongly recommend you to migrate to Octavia MICC instead, which can integrate strongly with the rest of the Octavia ecosystem. This compatibility layer only provides up-to-date SMF support (type 0, type 1, type 2; you also get free MUSEQ and XF extension support by migrating to this compatibility shim). */
export class ColxiMIDIParserBuffered extends ColxiMIDIParserBase {
	/** Parses the input into a structured representation.
	*
	* Note that unlike the original, this method is asynchronous. If the synchronous callback is not used, this requires an `await` statement or other ways to handle `Promise`s. This is due to some of the supported input types require asynchronous handling, contaminating others.
	* 
	* Because the MICC internals for file parsing upholds correctness quite strictly, malformed MIDI data accepted by the original implementation may become rejected by this shim.
	* @param input MIDI file data to be parsed. Like in the original implementation, this can be a Base64 string, one of the two `uint8` arrays, and a file input DOM object. This parser additionally supports an `ArrayBuffer`, a `File` object, or readable byte streams.
	* @param callback The method to invoke when parsing is finished. */
	static parse(input: UnifiedBinaryIntake, callback?: (file: ColxiMIDIFile) => void): Promise<ColxiMIDIFile>;
}

// `midi-json-tools/midi-to-json` and `chrisguttandin/midi-json-parser`

declare interface MJTControlChangeEventDetails {
	type: uint8;
	value: uint8;
}
declare interface MJTNoteToggleEventDetails {
	noteNumber: uint8;
	velocity: uint8;
}
declare interface MJTProgramEventDetails {
	programNumber: uint8;
}
declare interface MJTPressureEventDetails {
	pressure: uint8;
}
declare interface MJTNotePressureEventDetails extends MJTPressureEventDetails {
	noteNumber: uint8;
}
export interface MJTMIDIBaseEvent {
	/** MIDI delta time. */
	delta: uint32;
}
export interface MJTMIDIStatusEvent extends MJTMIDIBaseEvent {
	/** MIDI channel. */
	channel: uint8;
	/** Details for note aftertouch events. */
	channelPressure?: MJTPressureEventDetails;
	/** Details for control change events. */
	controlChange?: MJTControlChangeEventDetails;
	/** Details for note aftertouch events. */
	keyPressure?: MJTNotePressureEventDetails;
	/** Details for note off events. */
	noteOff?: MJTNoteToggleEventDetails;
	/** Details for note on events. */
	noteOn?: MJTNoteToggleEventDetails;
	/** Details for pitch bends. */
	pitchBend?: int16;
	/** Details for program changes. */
	programChange?: MJTProgramEventDetails;
	/** Details for SysEx events. */
	sysex?: string; // WTF is this design?! Why exposing an encoded string when `Uint8Array` is much more useful?! Have to use string here to follow the original schema.
}
declare interface MJTKeySignatureDetails {
	key: uint8;
	scale: uint8;
}
declare interface MJTSMPTEDetails {
	frame: uint8;
	frameRate: uint8;
	hour: uint8;
	minutes: uint8;
	seconds: uint8;
	subFrame: uint8;
}
declare interface MJTTempoDetails {
	microsecondsPerQuarter: uint32;
}
declare interface MJTTimeSignatureDetails {
	denominator: uint8;
	metronome: uint8;
	numerator: uint8;
	thirtyseconds: uint16;
}
export interface MJTMIDIMetaEvent extends MJTMIDIBaseEvent {
	/** Track channel events. */
	channelPrefix?: uint8;
	/** Copyright events. */
	copyrightNotice?: string;
	/** Cue point events. */
	cuePoint?: string;
	/** Device name events. */
	deviceName?: string;
	/** Track end events. */
	endOfTrack?: boolean;
	/** Instrument name events. */
	instrumentName?: string;
	/** Set key signature events. */
	keySignature?: MJTKeySignatureDetails;
	/** Lyrics events. */
	lyric?: string;
	/** Marker events. */
	marker?: string;
	/** Meta event type of unknown "text" events. */
	metaTypeByte?: string; // Why is not this a number??? Why does the original implementation specified by the documentation do this???
	/** Track port events. */
	midiPort?: uint8;
	/** Voice name events. */
	programName?: string;
	/** SeqEx events. */
	sequencerSpecificData?: string; // Really, this is a string just like the real deal. Seriously wondering whoever wrote this library never dealt with actual serious synth state tracking, this should be `Uint8Array` instead. I'm never using this schema myself, holy Moonbutt! Not removing this comment or apologising, this library is one of the examples of staying away from NPM.
	/** Set tempo events. */
	setTempo?: MJTTempoDetails;
	/** Set SMPTE offset events. */
	smpteOffset?: MJTSMPTEDetails;
	/** Text events, as well as text payloads of unknown "text" events. */
	text?: string;
	/** Set time signature events. */
	timeSignature?: MJTTimeSignatureDetails;
	/** Track title events. */
	trackName?: string;
}
export interface MJTMIDIFile {
	/** MIDI file type (0, 1, 2). */
	format: uint16;
	/** The time division used by files. 480 is the most common value. */
	division: uint16;
	/** Actual tracks with events. */
	tracks: MJTMIDIStatusEvent[][]|MJTMIDIMetaEvent[][];
}
/** (WIP) Mostly a drop-in replacement for `midi-json-tools/midi-to-json` and `chrisguttandin/midi-json-parser`. Customised parser support has not been added yet.
*
* For extensive additional benefits, we strongly recommend you to migrate to Octavia MICC instead, which can integrate strongly with the rest of the Octavia ecosystem. This compatibility layer only provides up-to-date SMF support (type 0, type 1, type 2; you also get free MUSEQ and XF extension support by migrating to this compatibility shim). */
export class MidiJsonTools {
	/** Parses the input into a structured representation. Entrypoint used by `midi-json-tools/midi-to-json`. Does not offer a Mojibake handler like the `ColxiMIDIParser` shim.
	*
	* Note that unlike the original, this method is asynchronous, requiring an `await` statement if callback is not used. This is due to the MICC internals prioritise the use of streams to minimise unnecessary resource usage.
	* 
	* Because the MICC internals for file parsing upholds correctness quite strictly, malformed MIDI data accepted by the original implementation may become rejected by this shim.
	* @param input MIDI file data to be parsed. Like in the original implementation, this can be an `ArrayBuffer`. This parser additionally supports a Base64 string, one of the two `uint8` arrays, a file input DOM object, a `File` object, or readable byte streams. */
	static midiToJson(input: UnifiedBinaryIntake): Promise<MJTMIDIFile>;
	/** Parses the input into a structured representation. Entrypoint used by `chrisguttandin/midi-json-parser`. Does not offer a Mojibake handler like the `ColxiMIDIParser` shim.
	* 
	* Because the MICC internals for file parsing upholds correctness quite strictly, malformed MIDI data accepted by the original implementation may become rejected by this shim.
	* @param input MIDI file data to be parsed. Like in the original implementation, this can be an `ArrayBuffer`. This parser additionally supports a Base64 string, one of the two `uint8` arrays, a file input DOM object, a `File` object, or readable byte streams. */
	static parseArrayBuffer(input: UnifiedBinaryIntake): Promise<MJTMIDIFile>;
	/** A list of text decoders to be used. Not present in the original implementations, this is added to allow correct decoding of MIDI files having multiple text encodings, a practical defense against Mojibake. */
	static decoders?: Iterable<TextDecoder>;
	/** When `true`, the parser will also include extensions not seen in regular MIDI files that MICC supports (e.g. XF, MUSEQ). Defaults to `true`.
	*
	* Not present in the original implementation. */
	static extended: boolean;
}

// `jokr/midi-node`, but not implemented for now, since it was Node-centric with no browser compatibility facing.

// The `@gasman/jasmid/midifile.js` family: `carter-thaxton/midi-file` and `ryohey/midifile-ts`, but not implemented for now, since they were quite Node-centric. Priority probably higher than `jokr/midi-node` too. Also not sure about implementing the write side of some of the children.
