// 2022-2026 © Lightingale Community
// Licensed under GNU LGPL v3.0 license.

/** Robust compatibility layers for the Musical Instructions Compiler Collection. For additional benefits, such as [extensive file import and export support](https://kb.ltgc.cc/octavia/impl/format.html) and MIDI 2.0 wire format support, provided by the MICC subsystem, or such as synth behaviour emulation, and extended standard compliance, provided by the Octavia state engine, we strongly recommend you to migrate to Octavia MICC ([Codeberg](https://codeberg.org/ltgc/octavia/), [GitHub](https://github.com/ltgcgo/octavia/), [JSR](https://jsr.io/@ltgc/octavia/doc/micc/)) instead, which can integrate strongly with the rest of the Octavia ecosystem.
*
* This module is also released standalone as `@ltgc/midi-parser-ecosystem` on NPM and JSR to allow transitioning off said ecosystems, as well as for SEO due to poor search index ranking on package manager repositories and search engines. This module does **not** incorporate code generated by LLMs.
*
* @example
* ```js
* // Colxi MIDI Parser
* import {ColxiMIDIParser} from "path_to_js_file";
* const midiFile = await ColxiMIDIParser.parse(input);
* // MIDI JSON Tools Parser or C. Guttandin MIDI JSON Parser
* import {MidiJsonTools} from "path_to_js_file";
* const midiFile = await MidiJsonTools.midiToJson(input); // MIDI JSON Tools
* const midiFile = await MidiJsonTools.parseArrayBuffer(input); // C. Guttandin
* ```
* @license LGPL-3.0-only
* @module cc.ltgc.octavia.miccCompat
*/

import type {
	uint8,
	uint16,
	uint32,
	int16
} from "../../libs/seamstress@ltgcgo/nativeType/index.d.mts";

// `colxi/midi-parser-js`

/** A MIDI event in the `colxi/midi-parser-js` scheme. */
declare interface ColxiMIDIEvent {
	/** MIDI channel. */
	channel?: uint8;
	/** MIDI delta time. */
	deltaTime: uint32;
	/** MIDI event type. Note that event type `240` (SysEx) from MICC will be converted to type `15` instead to support behaviour. */
	type: uint8;
	/** If the event is a meta event, the meta event type. */
	metaType?: uint8;
	/** Actual data of the event. */
	data?: number|Uint8Array|string;
}
/** A MIDI track containing events in the `colxi/midi-parser-js` scheme. */
declare interface ColxiMIDITrack {
	/** List of events populated by the track. */
	event: ColxiMIDIEvent[];
	/** The type of the track. Not present in the original implementation. */
	type: string;
}
/** The representation of a parsed MIDI file in the `colxi/midi-parser-js` scheme. */
declare interface ColxiMIDIFile {
	/** MIDI file type (0, 1, 2). */
	formatType: uint16;
	/** The time division used by files. 480 is the most common value. */
	timeDivision: uint16;
	/** Number of expected tracks specified by the MIDI file. Not guaranteed to the the exact number of tracks supplied by the MIDI file. */
	tracks: number;
	/** Actual tracks with events. */
	track: ColxiMIDITrack[];
}
/** View into each Colxi MIDI event, supplied to `ColxiMIDIParser.customInterpreter`. Will only be supplied for 0xf0 events. */
declare interface ColxiMIDIView {
	/** The data of the event. Unlike the original implementatino, this only grants view of the current event. */
	data: DataView;
	/** The pointer of the current event. When invoked, for 0xf0 events, the pointer will sit on the SysEx length byte. */
	pointer: number;
	/** Move the apparent pointer. Unlike the original implementation, this method does not affect MIDI file parsing in any way, and is bound-checked.
	* @param offset The relative offset to move the pointer against. -1 moves the pointer to the previous byte, 0 has no effect, and 1 moves the pointer to the next byte.
	* @returns The mutated pointer. */
	movePointer(offset: number): number;
	/** Read multi-byte integers. */
	readInt(readSize: number): number;
	/** Read VLV-8 on the current pointer. */
	readIntVLV(): number;
	/** Read a string. If the `decoders` property of the parser object can be accessed, it will attempt to decode string supplied by the decoders in the `decoders` property, advancing to the next one whenever the current decoder fails. The catch-all decoder is X-ASCII. */
	readStr(readSize: number): string;
}
/** Mostly a drop-in replacement for the unmaintained `colxi/midi-parser-js`. If some files are proven to be problematic for the original implementation (e.g. with running status omission), migrating to Octavia's compatibility layer may help handle those files.
*
* For extensive additional benefits, we strongly recommend you to migrate to Octavia MICC instead, which can integrate strongly with the rest of the Octavia ecosystem. This compatibility layer only provides up-to-date SMF support (type 0, type 1, type 2; you also get free MUSEQ and XF extension support by migrating to this compatibility shim). */
export class ColxiMIDIParser {
	/** Parses the input into a structured representation.
	*
	* Note that unlike the original, this method is asynchronous, requiring an `await` statement if callback is not used. This is due to the MICC internals prioritise the use of streams to minimise unnecessary resource usage.
	* 
	* Because the MICC internals for file parsing upholds correctness quite strictly, malformed MIDI data accepted by the original implementation may become rejected by this shim.
	* @param input MIDI file data to be parsed. Like in the original implementation, this can be a Base64 string, one of the two `uint8` arrays, and a file input DOM object. This parser additionally supports an `ArrayBuffer`, a `File` object, a hexadecimal string, or readable byte streams.
	* @param callback The method to invoke when parsing is finished. */
	static parse(input: string|ArrayBuffer|Uint8Array|Uint8ClampedArray|HTMLInputElement|Blob|File|ReadableStream<Uint8Array>|AsyncIterable<Uint8Array>, callback?: (file: ColxiMIDIFile) => void): Promise<ColxiMIDIFile>;
	/** Defines custom interpreter behaviour, should only invoked by the parser. The returned value will populate the data property. Returning `false` will assume default behaviour.
	*
	* Unlike in the original parser, you will get the original unparsed bytes by default. Set this property to `null` or `undefined` to prevent this behaviour.
	* @param type The event type.
	* @param view A view into the MIDI data currently being parsed.
	* @param metaLength Length of the meta event. Will only be present for 0xff events. */
	static customInterpreter?: (type: number, view: ColxiMIDIView, metaLength?: number) => any;
	/** A list of text decoders to be used. Not present in the original implementation, this is added to allow correct decoding of MIDI files having multiple text encodings, a practical defense against Mojibake. */
	static decoders?: Iterable<TextDecoder>;
}

// `midi-json-tools/midi-to-json` and `chrisguttandin/midi-json-parser`

declare interface MJTControlChangeEventDetails {
	type: uint8;
	value: uint8;
}
declare interface MJTNoteToggleEventDetails {
	noteNumber: uint8;
	velocity: uint8;
}
declare interface MJTProgramEventDetails {
	programNumber: uint8;
}
declare interface MJTPressureEventDetails {
	pressure: uint8;
}
declare interface MJTNotePressureEventDetails extends MJTPressureEventDetails {
	noteNumber: uint8;
}
export interface MJTMIDIBaseEvent {
	/** MIDI delta time. */
	delta: uint32;
}
export interface MJTMIDIStatusEvent extends MJTMIDIBaseEvent {
	/** MIDI channel. */
	channel: uint8;
	/** Details for note aftertouch events. */
	channelPressure?: MJTPressureEventDetails;
	/** Details for control change events. */
	controlChange?: MJTControlChangeEventDetails;
	/** Details for note aftertouch events. */
	keyPressure?: MJTNotePressureEventDetails;
	/** Details for note off events. */
	noteOff?: MJTNoteToggleEventDetails;
	/** Details for note on events. */
	noteOn?: MJTNoteToggleEventDetails;
	/** Details for pitch bends. */
	pitchBend?: int16;
	/** Details for program changes. */
	programChange?: MJTProgramEventDetails;
	/** Details for SysEx events. */
	sysex?: string; // WTF is this design?! Why exposing an encoded string when `Uint8Array` is much more useful?! Have to use string here to follow the original schema.
}
declare interface MJTKeySignatureDetails {
	key: uint8;
	scale: uint8;
}
declare interface MJTSMPTEDetails {
	frame: uint8;
	frameRate: uint8;
	hour: uint8;
	minutes: uint8;
	seconds: uint8;
	subFrame: uint8;
}
declare interface MJTTempoDetails {
	microsecondsPerQuarter: uint32;
}
declare interface MJTTimeSignatureDetails {
	denominator: uint8;
	metronome: uint8;
	numerator: uint8;
	thirtyseconds: uint16;
}
export interface MJTMIDIMetaEvent extends MJTMIDIBaseEvent {
	/** Track channel events. */
	channelPrefix?: uint8;
	/** Copyright events. */
	copyrightNotice?: string;
	/** Cue point events. */
	cuePoint?: string;
	/** Device name events. */
	deviceName?: string;
	/** Track end events. */
	endOfTrack?: boolean;
	/** Instrument name events. */
	instrumentName?: string;
	/** Set key signature events. */
	keySignature?: MJTKeySignatureDetails;
	/** Lyrics events. */
	lyric?: string;
	/** Marker events. */
	marker?: string;
	/** Meta event type of unknown "text" events. */
	metaTypeByte?: string; // Why is not this a number??? Why does the original implementation specified by the documentation do this???
	/** Track port events. */
	midiPort?: uint8;
	/** Voice name events. */
	programName?: string;
	/** SeqEx events. */
	sequencerSpecificData?: string; // Really, this is a string just like the real deal. Seriously wondering whoever wrote this library never dealt with actual serious synth state tracking, this should be `Uint8Array` instead. I'm never using this schema myself, holy Moonbutt! Not removing this comment or apologising, this library is one of the examples of staying away from NPM.
	/** Set tempo events. */
	setTempo?: MJTTempoDetails;
	/** Set SMPTE offset events. */
	smpteOffset?: MJTSMPTEDetails;
	/** Text events, as well as text payloads of unknown "text" events. */
	text?: string;
	/** Set time signature events. */
	timeSignature?: MJTTimeSignatureDetails;
	/** Track title events. */
	trackName?: string;
}
export interface MJTMIDIFile {
	/** MIDI file type (0, 1, 2). */
	format: uint16;
	/** The time division used by files. 480 is the most common value. */
	division: uint16;
	/** Actual tracks with events. */
	tracks: MJTMIDIStatusEvent[][]|MJTMIDIMetaEvent[][];
}
/** Mostly a drop-in replacement for `midi-json-tools/midi-to-json` and `chrisguttandin/midi-json-parser`. Customised parser support has not been added yet.
*
* For extensive additional benefits, we strongly recommend you to migrate to Octavia MICC instead, which can integrate strongly with the rest of the Octavia ecosystem. This compatibility layer only provides up-to-date SMF support (type 0, type 1, type 2; you also get free MUSEQ and XF extension support by migrating to this compatibility shim). */
export class MidiJsonTools {
	/** Parses the input into a structured representation. Entrypoint used by `midi-json-tools/midi-to-json`. Does not offer a Mojibake handler like the `ColxiMIDIParser` shim.
	*
	* Note that unlike the original, this method is asynchronous, requiring an `await` statement if callback is not used. This is due to the MICC internals prioritise the use of streams to minimise unnecessary resource usage.
	* 
	* Because the MICC internals for file parsing upholds correctness quite strictly, malformed MIDI data accepted by the original implementation may become rejected by this shim.
	* @param input MIDI file data to be parsed. Like in the original implementation, this can be an `ArrayBuffer`. This parser additionally supports a Base64 string, one of the two `uint8` arrays, a file input DOM object, a `File` object, a hexadecimal string, or readable byte streams. */
	static midiToJson(input: string|ArrayBuffer|Uint8Array|Uint8ClampedArray|HTMLInputElement|Blob|File|ReadableStream<Uint8Array>|AsyncIterable<Uint8Array>): Promise<MJTMIDIFile>;
	/** Parses the input into a structured representation. Entrypoint used by `chrisguttandin/midi-json-parser`. Does not offer a Mojibake handler like the `ColxiMIDIParser` shim.
	* 
	* Because the MICC internals for file parsing upholds correctness quite strictly, malformed MIDI data accepted by the original implementation may become rejected by this shim.
	* @param input MIDI file data to be parsed. Like in the original implementation, this can be an `ArrayBuffer`. This parser additionally supports a Base64 string, one of the two `uint8` arrays, a file input DOM object, a `File` object, a hexadecimal string, or readable byte streams. */
	static parseArrayBuffer(input: string|ArrayBuffer|Uint8Array|Uint8ClampedArray|HTMLInputElement|Blob|File|ReadableStream<Uint8Array>|AsyncIterable<Uint8Array>): Promise<MJTMIDIFile>;
}
